version: '3.8'

services:
  livekit-agent:
    build: .
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}
      - RUBE_API_KEY=${RUBE_API_KEY}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - livekit-network

networks:
  livekit-network:
    driver: bridge
